go:
    version: 1.23
    cgo: true

repository:
    path: github.com/galexrt/extended-ceph-exporter

build:
    flags: '-a -tags netgo'
    static: false
    ldflags: |
        -s
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}

    binaries:
        - name: extended-ceph-exporter
          path: "."

tarball:
    files:
        - LICENSE

crossbuild:
    platforms:
        - linux/amd64
        - linux/arm64
